-- Total business revenue
SELECT 
    SUM(revenue) AS total_revenue
FROM orders_final;



-- Revenue generated by each product
SELECT 
    product_name,
    SUM(revenue) AS total_revenue
FROM orders_final
GROUP BY product_name
ORDER BY total_revenue DESC;



-- Top 5 products by revenue
WITH product_revenue AS (
    SELECT 
        product_name,
        SUM(revenue) AS total_revenue
    FROM orders_final
    GROUP BY product_name
)

SELECT *
FROM product_revenue
ORDER BY total_revenue DESC
LIMIT 5;



-- Revenue by region
SELECT 
    region,
    SUM(revenue) AS total_revenue
FROM orders_final
GROUP BY region
ORDER BY total_revenue DESC;



-- Top 5 customers by spending
WITH customer_revenue AS (
    SELECT 
        customer_id,
        SUM(revenue) AS total_revenue
    FROM orders_final
    GROUP BY customer_id
)

SELECT *
FROM customer_revenue
ORDER BY total_revenue DESC
LIMIT 5;



-- Monthly revenue trend
SELECT 
    MONTH(order_date) AS month,
    SUM(revenue) AS total_revenue
FROM orders_final
GROUP BY month
ORDER BY month;



-- Customer purchase behavior
SELECT 
    customer_id,
    COUNT(order_id) AS total_orders,
    SUM(revenue) AS total_spent,
    AVG(revenue) AS avg_order_value
FROM orders_final
GROUP BY customer_id;



-- Order status analysis
SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders_final
GROUP BY order_status;



-- Revenue loss from returned orders
SELECT 
    SUM(price * quantity) AS lost_revenue
FROM orders_final
WHERE order_status = 'Returned';



-- Revenue by category
SELECT 
    category,
    SUM(revenue) AS total_revenue
FROM orders_final
GROUP BY category
ORDER BY total_revenue DESC;